/**
 * POST /api/support/conversations/[id]/reply
 *
 * Two modes:
 *   mode: 'human'  → just save the staff message as outbound. No AI call.
 *                    (Optionally trigger WhatsApp send, gated by env.)
 *   mode: 'ai'     → run the agent ONCE on the latest customer message and
 *                    return the AI reply. Saves both messages to DB.
 *
 * Body:
 *   {
 *     mode: 'human' | 'ai',
 *     body?: string   (required for mode='human')
 *   }
 *
 * Hard rules:
 *   ✗ Never auto-send refunds, coupons, money
 *   ✓ Every human reply is logged with author_email
 *   ✓ WhatsApp send is optional (returns ok=true even if creds missing)
 */
import { z } from 'zod';
import { NextRequest } from 'next/server';
import { ok, err, withErrorHandling } from '@/lib/api-response';
import { getActor } from '@/lib/actor';
import { createAdminSupabaseClient } from '@/lib/supabase/server';
import { runWhatsappAgent } from '@/lib/agent/agent';
import { sendWhatsappText } from '@/lib/whatsapp';

export const runtime = 'nodejs';
export const maxDuration = 60;

type Ctx = { params: { id: string } };

const Body = z.union([
  z.object({ mode: z.literal('human'), body: z.string().min(1).max(4000) }),
  z.object({ mode: z.literal('ai') }),
]);

export const POST = withErrorHandling(async (req: NextRequest, ctx: Ctx) => {
  const actor = await getActor();
  if (!['owner', 'editor'].includes(actor.role)) {
    return err('FORBIDDEN', `Role ${actor.role} cannot reply`, 403);
  }

  const id = Number(ctx.params.id);
  if (!Number.isFinite(id)) return err('BAD_ID', 'Invalid conversation id', 400);

  const body = Body.parse(await req.json());
  const admin = createAdminSupabaseClient();

  // Load conversation
  const { data: conv, error: cErr } = await admin
    .from('conversations')
    .select('id, customer_phone, customer_name, language, ai_enabled, status, total_messages')
    .eq('id', id)
    .maybeSingle();
  if (cErr || !conv) return err('NOT_FOUND', 'Conversation not found', 404);

  // ─── HUMAN MODE ───────────────────────────────────────────────────────────
  if (body.mode === 'human') {
    const { data: inserted, error: insErr } = await admin
      .from('messages')
      .insert({
        conversation_id: id,
        direction: 'outbound',
        body: body.body,
        intent: 'human',
        // ai_model stays null → marks this as human-sent
      })
      .select('id, created_at')
      .single();
    if (insErr) return err('INSERT_FAILED', insErr.message, 500);

    // Audit note
    await admin.from('support_notes').insert({
      conversation_id: id,
      body: `Human reply sent (${body.body.length} chars)`,
      kind: 'action',
      author_email: actor.email,
      author_name: actor.email,
      metadata: { action: 'human_reply', message_id: inserted.id },
    });

    // Bump conversation aggregates
    await admin
      .from('conversations')
      .update({
        last_message_at: inserted.created_at,
        last_read_at: new Date().toISOString(),
        total_messages: (conv.total_messages ?? 0) + 1,
      })
      .eq('id', id);

    // Try to send over WhatsApp (non-fatal if not configured)
    const send = await sendWhatsappText({
      to: conv.customer_phone,
      body: body.body,
    });

    return ok({
      message_id: inserted.id,
      sent_to_whatsapp: send.ok,
      whatsapp_reason: send.ok ? undefined : send.reason,
    });
  }

  // ─── AI MODE ──────────────────────────────────────────────────────────────
  // Pull the last inbound message and run the agent on it.
  const { data: lastInbound } = await admin
    .from('messages')
    .select('body, media_url')
    .eq('conversation_id', id)
    .eq('direction', 'inbound')
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!lastInbound) {
    return err('NO_INBOUND', 'No inbound message to respond to', 400);
  }

  const result = await runWhatsappAgent({
    customer_phone: conv.customer_phone,
    customer_name: conv.customer_name ?? undefined,
    message_body: lastInbound.body,
    media_url: lastInbound.media_url ?? undefined,
  });

  // Audit
  await admin.from('support_notes').insert({
    conversation_id: id,
    body: `AI reply generated by staff trigger (${result.usage.input_tokens}+${result.usage.output_tokens} tokens)`,
    kind: 'action',
    author_email: actor.email,
    author_name: actor.email,
    metadata: {
      action: 'ai_reply',
      cost_usd: result.usage.cost_usd,
      escalations: result.escalations.length,
    },
  });

  return ok({
    reply: result.reply,
    matched_products: result.matched_products,
    escalations: result.escalations,
    tool_calls: result.tool_calls,
    usage: result.usage,
  });
});
