/**
 * Supabase `Database` types — RECONSTRUCTED FROM COMMITTED MIGRATIONS.
 *
 * ⚠️ These types are NOT generated from a live database. `pnpm db:types`
 * (`supabase gen types --linked`) was intentionally NOT run — it requires a
 * connection to the remote/production project. Instead, this file is hand-built
 * strictly from the SQL committed in `supabase/migrations/*.sql`
 * (00000000000000_initial → 00000000000025_master_products), aggregating each
 * table's `CREATE TABLE` with every later `ALTER TABLE ... ADD COLUMN`.
 *
 * Scope: every table/view/function referenced by application code
 * (`apps/web`, `apps/workers`). Type conventions follow `supabase gen types`:
 *   int/serial/bigint/smallint/numeric → number
 *   text/citext/uuid/timestamptz/vector → string
 *   boolean → boolean; jsonb → Json; text[] → string[]; bigint[] → number[]
 * A column is `| null` unless declared NOT NULL. In Insert, a field is required
 * only when it is NOT NULL, has no DEFAULT, and is not an auto serial PK.
 *
 * When regenerating against a real environment later, replace this file with the
 * CLI output (`pnpm db:types`). Tables not used by code (e.g. master_products,
 * master_import_runs) are intentionally omitted; add them if code starts using
 * them.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: number;
          name: string;
          code: string;
          name_ar: string | null;
          priority: number;
          display_order: number | null;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          code: string;
          name_ar?: string | null;
          priority: number;
          display_order?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          code?: string;
          name_ar?: string | null;
          priority?: number;
          display_order?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      subcategories: {
        Row: {
          id: number;
          category_id: number;
          name: string;
          name_ar: string | null;
          display_order: number | null;
          is_active: boolean | null;
        };
        Insert: {
          id?: number;
          category_id: number;
          name: string;
          name_ar?: string | null;
          display_order?: number | null;
          is_active?: boolean | null;
        };
        Update: {
          id?: number;
          category_id?: number;
          name?: string;
          name_ar?: string | null;
          display_order?: number | null;
          is_active?: boolean | null;
        };
        Relationships: [];
      };
      brands: {
        Row: {
          id: number;
          name: string;
          name_ar: string | null;
          code: string | null;
          country_origin: string | null;
          logo_url: string | null;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          name_ar?: string | null;
          code?: string | null;
          country_origin?: string | null;
          logo_url?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          name_ar?: string | null;
          code?: string | null;
          country_origin?: string | null;
          logo_url?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      category_rules: {
        Row: {
          id: number;
          brand_id: number;
          category_id: number;
          default_subcategory_id: number | null;
          confidence: number | null;
        };
        Insert: {
          id?: number;
          brand_id: number;
          category_id: number;
          default_subcategory_id?: number | null;
          confidence?: number | null;
        };
        Update: {
          id?: number;
          brand_id?: number;
          category_id?: number;
          default_subcategory_id?: number | null;
          confidence?: number | null;
        };
        Relationships: [];
      };
      keyword_rules: {
        Row: {
          id: number;
          keyword: string;
          language: string;
          category_id: number | null;
          subcategory_id: number | null;
          confidence: number | null;
        };
        Insert: {
          id?: number;
          keyword: string;
          language: string;
          category_id?: number | null;
          subcategory_id?: number | null;
          confidence?: number | null;
        };
        Update: {
          id?: number;
          keyword?: string;
          language?: string;
          category_id?: number | null;
          subcategory_id?: number | null;
          confidence?: number | null;
        };
        Relationships: [];
      };
      sku_counter: {
        Row: { prefix: string; sequence: number; updated_at: string | null };
        Insert: { prefix: string; sequence?: number; updated_at?: string | null };
        Update: { prefix?: string; sequence?: number; updated_at?: string | null };
        Relationships: [];
      };
      products: {
        Row: {
          id: number;
          master_sku: string;
          detailed_sku: string | null;
          snoonu_sku: string | null;
          barcode: string | null;
          product_name_en: string;
          product_name_ar: string;
          brand_id: number;
          category_id: number;
          subcategory_id: number | null;
          product_type: string | null;
          variant: string | null;
          color: string | null;
          size: string | null;
          price: number;
          discount_price: number | null;
          cost: number | null;
          stock_quantity: number;
          stock_status: string;
          product_status: string;
          image_url: string | null;
          image_filename: string | null;
          description_en: string | null;
          description_ar: string | null;
          keywords_en: string[] | null;
          keywords_ar: string[] | null;
          source_platform: string;
          embedding: string | null;
          created_at: string | null;
          updated_at: string | null;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          usage_en: string | null;
          usage_ar: string | null;
          ai_generated: boolean | null;
          ai_confidence: number | null;
          ai_meta: Json | null;
          shopify_product_id: number | null;
          shopify_handle: string | null;
          shopify_synced_at: string | null;
          readiness_score: number | null;
          readiness_meta: Json | null;
          snoonu_url: string | null;
        };
        Insert: {
          id?: number;
          // master_sku is NOT NULL but auto-filled by the `auto_assign_master_sku`
          // trigger when omitted, so it is optional at insert time.
          master_sku?: string;
          detailed_sku?: string | null;
          snoonu_sku?: string | null;
          barcode?: string | null;
          product_name_en: string;
          product_name_ar: string;
          brand_id: number;
          category_id: number;
          subcategory_id?: number | null;
          product_type?: string | null;
          variant?: string | null;
          color?: string | null;
          size?: string | null;
          price: number;
          discount_price?: number | null;
          cost?: number | null;
          stock_quantity?: number;
          stock_status?: string;
          product_status?: string;
          image_url?: string | null;
          image_filename?: string | null;
          description_en?: string | null;
          description_ar?: string | null;
          keywords_en?: string[] | null;
          keywords_ar?: string[] | null;
          source_platform?: string;
          embedding?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          usage_en?: string | null;
          usage_ar?: string | null;
          ai_generated?: boolean | null;
          ai_confidence?: number | null;
          ai_meta?: Json | null;
          shopify_product_id?: number | null;
          shopify_handle?: string | null;
          shopify_synced_at?: string | null;
          readiness_score?: number | null;
          readiness_meta?: Json | null;
          snoonu_url?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          detailed_sku?: string | null;
          snoonu_sku?: string | null;
          barcode?: string | null;
          product_name_en?: string;
          product_name_ar?: string;
          brand_id?: number;
          category_id?: number;
          subcategory_id?: number | null;
          product_type?: string | null;
          variant?: string | null;
          color?: string | null;
          size?: string | null;
          price?: number;
          discount_price?: number | null;
          cost?: number | null;
          stock_quantity?: number;
          stock_status?: string;
          product_status?: string;
          image_url?: string | null;
          image_filename?: string | null;
          description_en?: string | null;
          description_ar?: string | null;
          keywords_en?: string[] | null;
          keywords_ar?: string[] | null;
          source_platform?: string;
          embedding?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          usage_en?: string | null;
          usage_ar?: string | null;
          ai_generated?: boolean | null;
          ai_confidence?: number | null;
          ai_meta?: Json | null;
          shopify_product_id?: number | null;
          shopify_handle?: string | null;
          shopify_synced_at?: string | null;
          readiness_score?: number | null;
          readiness_meta?: Json | null;
          snoonu_url?: string | null;
        };
        Relationships: [];
      };
      product_images: {
        Row: {
          id: number;
          master_sku: string;
          r2_key: string;
          cdn_url: string;
          filename: string;
          is_primary: boolean | null;
          width: number | null;
          height: number | null;
          format: string | null;
          file_size_kb: number | null;
          phash: string | null;
          is_broken: boolean | null;
          uploaded_at: string | null;
          uploaded_by: string | null;
          source_platform: string | null;
          source_url: string | null;
          import_item_id: number | null;
        };
        Insert: {
          id?: number;
          master_sku: string;
          r2_key: string;
          cdn_url: string;
          filename: string;
          is_primary?: boolean | null;
          width?: number | null;
          height?: number | null;
          format?: string | null;
          file_size_kb?: number | null;
          phash?: string | null;
          is_broken?: boolean | null;
          uploaded_at?: string | null;
          uploaded_by?: string | null;
          source_platform?: string | null;
          source_url?: string | null;
          import_item_id?: number | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          r2_key?: string;
          cdn_url?: string;
          filename?: string;
          is_primary?: boolean | null;
          width?: number | null;
          height?: number | null;
          format?: string | null;
          file_size_kb?: number | null;
          phash?: string | null;
          is_broken?: boolean | null;
          uploaded_at?: string | null;
          uploaded_by?: string | null;
          source_platform?: string | null;
          source_url?: string | null;
          import_item_id?: number | null;
        };
        Relationships: [];
      };
      platform_mappings: {
        Row: {
          id: number;
          master_sku: string;
          platform: string;
          platform_product_id: string | null;
          platform_sku: string | null;
          platform_price: number | null;
          platform_status: string | null;
          platform_url: string | null;
          last_synced_at: string | null;
          last_sync_status: string | null;
          sync_error: string | null;
        };
        Insert: {
          id?: number;
          master_sku: string;
          platform: string;
          platform_product_id?: string | null;
          platform_sku?: string | null;
          platform_price?: number | null;
          platform_status?: string | null;
          platform_url?: string | null;
          last_synced_at?: string | null;
          last_sync_status?: string | null;
          sync_error?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          platform?: string;
          platform_product_id?: string | null;
          platform_sku?: string | null;
          platform_price?: number | null;
          platform_status?: string | null;
          platform_url?: string | null;
          last_synced_at?: string | null;
          last_sync_status?: string | null;
          sync_error?: string | null;
        };
        Relationships: [];
      };
      inventory: {
        Row: {
          id: number;
          master_sku: string;
          change_type: string;
          quantity_delta: number;
          quantity_after: number;
          reason: string | null;
          platform: string | null;
          reference_id: string | null;
          actor: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          master_sku: string;
          change_type: string;
          quantity_delta: number;
          quantity_after: number;
          reason?: string | null;
          platform?: string | null;
          reference_id?: string | null;
          actor?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          change_type?: string;
          quantity_delta?: number;
          quantity_after?: number;
          reason?: string | null;
          platform?: string | null;
          reference_id?: string | null;
          actor?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      price_history: {
        Row: {
          id: number;
          master_sku: string;
          old_price: number | null;
          new_price: number;
          old_discount: number | null;
          new_discount: number | null;
          reason: string | null;
          actor: string | null;
          changed_at: string | null;
        };
        Insert: {
          id?: number;
          master_sku: string;
          old_price?: number | null;
          new_price: number;
          old_discount?: number | null;
          new_discount?: number | null;
          reason?: string | null;
          actor?: string | null;
          changed_at?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          old_price?: number | null;
          new_price?: number;
          old_discount?: number | null;
          new_discount?: number | null;
          reason?: string | null;
          actor?: string | null;
          changed_at?: string | null;
        };
        Relationships: [];
      };
      product_logs: {
        Row: {
          id: number;
          master_sku: string;
          field_name: string;
          old_value: Json | null;
          new_value: Json | null;
          actor: string | null;
          source: string | null;
          changed_at: string | null;
        };
        Insert: {
          id?: number;
          master_sku: string;
          field_name: string;
          old_value?: Json | null;
          new_value?: Json | null;
          actor?: string | null;
          source?: string | null;
          changed_at?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string;
          field_name?: string;
          old_value?: Json | null;
          new_value?: Json | null;
          actor?: string | null;
          source?: string | null;
          changed_at?: string | null;
        };
        Relationships: [];
      };
      validation_issues: {
        Row: {
          id: number;
          master_sku: string | null;
          rule_id: string;
          severity: string;
          field_name: string | null;
          message: string;
          suggested_fix: string | null;
          status: string;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          master_sku?: string | null;
          rule_id: string;
          severity: string;
          field_name?: string | null;
          message: string;
          suggested_fix?: string | null;
          status?: string;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string | null;
          rule_id?: string;
          severity?: string;
          field_name?: string | null;
          message?: string;
          suggested_fix?: string | null;
          status?: string;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ai_training_data: {
        Row: {
          id: number;
          type: string;
          question: string;
          answer: string;
          language: string;
          master_sku: string | null;
          embedding: string | null;
          tags: string[] | null;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          type: string;
          question: string;
          answer: string;
          language: string;
          master_sku?: string | null;
          embedding?: string | null;
          tags?: string[] | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          type?: string;
          question?: string;
          answer?: string;
          language?: string;
          master_sku?: string | null;
          embedding?: string | null;
          tags?: string[] | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: number;
          customer_phone: string;
          customer_name: string | null;
          language: string | null;
          last_message_at: string | null;
          status: string | null;
          escalated: boolean | null;
          total_messages: number | null;
          created_at: string | null;
          ai_enabled: boolean | null;
          priority: string | null;
          assigned_to: number | null;
          resolved_at: string | null;
          last_read_at: string | null;
          internal_tags: string[] | null;
        };
        Insert: {
          id?: number;
          customer_phone: string;
          customer_name?: string | null;
          language?: string | null;
          last_message_at?: string | null;
          status?: string | null;
          escalated?: boolean | null;
          total_messages?: number | null;
          created_at?: string | null;
          ai_enabled?: boolean | null;
          priority?: string | null;
          assigned_to?: number | null;
          resolved_at?: string | null;
          last_read_at?: string | null;
          internal_tags?: string[] | null;
        };
        Update: {
          id?: number;
          customer_phone?: string;
          customer_name?: string | null;
          language?: string | null;
          last_message_at?: string | null;
          status?: string | null;
          escalated?: boolean | null;
          total_messages?: number | null;
          created_at?: string | null;
          ai_enabled?: boolean | null;
          priority?: string | null;
          assigned_to?: number | null;
          resolved_at?: string | null;
          last_read_at?: string | null;
          internal_tags?: string[] | null;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: number;
          conversation_id: number;
          direction: string;
          body: string;
          media_url: string | null;
          ai_model: string | null;
          ai_confidence: number | null;
          intent: string | null;
          tools_called: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id: number;
          direction: string;
          body: string;
          media_url?: string | null;
          ai_model?: string | null;
          ai_confidence?: number | null;
          intent?: string | null;
          tools_called?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number;
          direction?: string;
          body?: string;
          media_url?: string | null;
          ai_model?: string | null;
          ai_confidence?: number | null;
          intent?: string | null;
          tools_called?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      escalations: {
        Row: {
          id: number;
          conversation_id: number | null;
          customer_phone: string;
          reason: string;
          severity: string;
          summary: string | null;
          assigned_to: string | null;
          status: string;
          resolution_notes: string | null;
          sla_due_at: string | null;
          resolved_at: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id?: number | null;
          customer_phone: string;
          reason: string;
          severity: string;
          summary?: string | null;
          assigned_to?: string | null;
          status?: string;
          resolution_notes?: string | null;
          sla_due_at?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number | null;
          customer_phone?: string;
          reason?: string;
          severity?: string;
          summary?: string | null;
          assigned_to?: string | null;
          status?: string;
          resolution_notes?: string | null;
          sla_due_at?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      import_batches: {
        Row: {
          id: number;
          filename: string;
          source_platform: string | null;
          total_rows: number | null;
          success_rows: number | null;
          error_rows: number | null;
          skipped_rows: number | null;
          status: string;
          started_at: string | null;
          completed_at: string | null;
          initiated_by: string | null;
          error_summary: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          filename: string;
          source_platform?: string | null;
          total_rows?: number | null;
          success_rows?: number | null;
          error_rows?: number | null;
          skipped_rows?: number | null;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          initiated_by?: string | null;
          error_summary?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          filename?: string;
          source_platform?: string | null;
          total_rows?: number | null;
          success_rows?: number | null;
          error_rows?: number | null;
          skipped_rows?: number | null;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          initiated_by?: string | null;
          error_summary?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      import_errors: {
        Row: {
          id: number;
          batch_id: number;
          row_number: number | null;
          raw_data: Json | null;
          error_type: string | null;
          error_message: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          batch_id: number;
          row_number?: number | null;
          raw_data?: Json | null;
          error_type?: string | null;
          error_message?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          batch_id?: number;
          row_number?: number | null;
          raw_data?: Json | null;
          error_type?: string | null;
          error_message?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      review_queue: {
        Row: {
          id: number;
          master_sku: string | null;
          review_type: string;
          confidence: number | null;
          suggested_value: Json | null;
          current_value: Json | null;
          evidence: Json | null;
          status: string;
          reviewed_by: string | null;
          reviewer_notes: string | null;
          sla_due_at: string | null;
          resolved_at: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          master_sku?: string | null;
          review_type: string;
          confidence?: number | null;
          suggested_value?: Json | null;
          current_value?: Json | null;
          evidence?: Json | null;
          status?: string;
          reviewed_by?: string | null;
          reviewer_notes?: string | null;
          sla_due_at?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          master_sku?: string | null;
          review_type?: string;
          confidence?: number | null;
          suggested_value?: Json | null;
          current_value?: Json | null;
          evidence?: Json | null;
          status?: string;
          reviewed_by?: string | null;
          reviewer_notes?: string | null;
          sla_due_at?: string | null;
          resolved_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      automation_log: {
        Row: {
          id: number;
          workflow_name: string;
          execution_id: string | null;
          started_at: string;
          finished_at: string | null;
          status: string;
          rows_processed: number | null;
          duration_ms: number | null;
          errors: Json | null;
          metadata: Json | null;
        };
        Insert: {
          id?: number;
          workflow_name: string;
          execution_id?: string | null;
          started_at: string;
          finished_at?: string | null;
          status: string;
          rows_processed?: number | null;
          duration_ms?: number | null;
          errors?: Json | null;
          metadata?: Json | null;
        };
        Update: {
          id?: number;
          workflow_name?: string;
          execution_id?: string | null;
          started_at?: string;
          finished_at?: string | null;
          status?: string;
          rows_processed?: number | null;
          duration_ms?: number | null;
          errors?: Json | null;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          role: string;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          role?: string;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          role?: string;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      system_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_by: string | null;
          updated_at: string | null;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string | null;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      ai_search_cache: {
        Row: {
          id: number;
          query_hash: string;
          query_text: string;
          query_language: string | null;
          result: Json;
          tools_called: string[] | null;
          hit_count: number;
          last_accessed: string | null;
          expires_at: string;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          query_hash: string;
          query_text: string;
          query_language?: string | null;
          result: Json;
          tools_called?: string[] | null;
          hit_count?: number;
          last_accessed?: string | null;
          expires_at: string;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          query_hash?: string;
          query_text?: string;
          query_language?: string | null;
          result?: Json;
          tools_called?: string[] | null;
          hit_count?: number;
          last_accessed?: string | null;
          expires_at?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ai_usage_log: {
        Row: {
          id: number;
          conversation_id: number | null;
          model: string;
          operation: string | null;
          input_tokens: number;
          output_tokens: number;
          cached_input_tokens: number | null;
          cost_usd: number | null;
          latency_ms: number | null;
          cache_hit: boolean | null;
          success: boolean;
          error_message: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id?: number | null;
          model: string;
          operation?: string | null;
          input_tokens?: number;
          output_tokens?: number;
          cached_input_tokens?: number | null;
          cost_usd?: number | null;
          latency_ms?: number | null;
          cache_hit?: boolean | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number | null;
          model?: string;
          operation?: string | null;
          input_tokens?: number;
          output_tokens?: number;
          cached_input_tokens?: number | null;
          cost_usd?: number | null;
          latency_ms?: number | null;
          cache_hit?: boolean | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ai_drafts: {
        Row: {
          id: number;
          image_url: string;
          original_filename: string | null;
          suggestion: Json;
          confidence: number | null;
          ai_meta: Json | null;
          status: string;
          error_code: string | null;
          error_message: string | null;
          failing_table: string | null;
          failing_payload: Json | null;
          created_by: string | null;
          created_at: string | null;
          recovered_at: string | null;
          recovered_master_sku: string | null;
        };
        Insert: {
          id?: number;
          image_url: string;
          original_filename?: string | null;
          suggestion: Json;
          confidence?: number | null;
          ai_meta?: Json | null;
          status?: string;
          error_code?: string | null;
          error_message?: string | null;
          failing_table?: string | null;
          failing_payload?: Json | null;
          created_by?: string | null;
          created_at?: string | null;
          recovered_at?: string | null;
          recovered_master_sku?: string | null;
        };
        Update: {
          id?: number;
          image_url?: string;
          original_filename?: string | null;
          suggestion?: Json;
          confidence?: number | null;
          ai_meta?: Json | null;
          status?: string;
          error_code?: string | null;
          error_message?: string | null;
          failing_table?: string | null;
          failing_payload?: Json | null;
          created_by?: string | null;
          created_at?: string | null;
          recovered_at?: string | null;
          recovered_master_sku?: string | null;
        };
        Relationships: [];
      };
      export_history: {
        Row: {
          id: number;
          target: string;
          format: string;
          filters: Json | null;
          product_count: number;
          blocked_count: number;
          file_bytes: number | null;
          filename: string | null;
          exported_by: string | null;
          exported_at: string | null;
          notes: string | null;
        };
        Insert: {
          id?: number;
          target: string;
          format: string;
          filters?: Json | null;
          product_count?: number;
          blocked_count?: number;
          file_bytes?: number | null;
          filename?: string | null;
          exported_by?: string | null;
          exported_at?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: number;
          target?: string;
          format?: string;
          filters?: Json | null;
          product_count?: number;
          blocked_count?: number;
          file_bytes?: number | null;
          filename?: string | null;
          exported_by?: string | null;
          exported_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      support_agents: {
        Row: {
          id: number;
          user_id: string | null;
          email: string;
          display_name: string;
          role: string;
          languages: string[] | null;
          is_active: boolean | null;
          avatar_url: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          email: string;
          display_name: string;
          role?: string;
          languages?: string[] | null;
          is_active?: boolean | null;
          avatar_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          email?: string;
          display_name?: string;
          role?: string;
          languages?: string[] | null;
          is_active?: boolean | null;
          avatar_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      conversation_assignments: {
        Row: {
          id: number;
          conversation_id: number;
          agent_id: number | null;
          action: string;
          reason: string | null;
          actor_email: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id: number;
          agent_id?: number | null;
          action: string;
          reason?: string | null;
          actor_email?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number;
          agent_id?: number | null;
          action?: string;
          reason?: string | null;
          actor_email?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      support_notes: {
        Row: {
          id: number;
          conversation_id: number;
          body: string;
          author_email: string;
          author_name: string | null;
          kind: string;
          visible_to_customer: boolean | null;
          metadata: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id: number;
          body: string;
          author_email: string;
          author_name?: string | null;
          kind?: string;
          visible_to_customer?: boolean | null;
          metadata?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number;
          body?: string;
          author_email?: string;
          author_name?: string | null;
          kind?: string;
          visible_to_customer?: boolean | null;
          metadata?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      conversation_tags: {
        Row: {
          id: number;
          conversation_id: number;
          tag: string;
          added_by: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id: number;
          tag: string;
          added_by?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: number;
          tag?: string;
          added_by?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      agent_conversation_reads: {
        Row: {
          agent_id: number;
          conversation_id: number;
          last_read_at: string;
        };
        Insert: {
          agent_id: number;
          conversation_id: number;
          last_read_at?: string;
        };
        Update: {
          agent_id?: number;
          conversation_id?: number;
          last_read_at?: string;
        };
        Relationships: [];
      };
      notification_events: {
        Row: {
          id: number;
          kind: string;
          severity: string;
          title: string;
          body: string | null;
          conversation_id: number | null;
          target_agent: number | null;
          metadata: Json | null;
          created_at: string | null;
          read_at: string | null;
        };
        Insert: {
          id?: number;
          kind: string;
          severity?: string;
          title: string;
          body?: string | null;
          conversation_id?: number | null;
          target_agent?: number | null;
          metadata?: Json | null;
          created_at?: string | null;
          read_at?: string | null;
        };
        Update: {
          id?: number;
          kind?: string;
          severity?: string;
          title?: string;
          body?: string | null;
          conversation_id?: number | null;
          target_agent?: number | null;
          metadata?: Json | null;
          created_at?: string | null;
          read_at?: string | null;
        };
        Relationships: [];
      };
      whatsapp_webhook_logs: {
        Row: {
          id: number;
          direction: string;
          phone: string | null;
          payload: Json;
          status: string;
          error_message: string | null;
          wamid: string | null;
          conversation_id: number | null;
          live_enabled: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          direction: string;
          phone?: string | null;
          payload?: Json;
          status: string;
          error_message?: string | null;
          wamid?: string | null;
          conversation_id?: number | null;
          live_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          direction?: string;
          phone?: string | null;
          payload?: Json;
          status?: string;
          error_message?: string | null;
          wamid?: string | null;
          conversation_id?: number | null;
          live_enabled?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      snoonu_import_batches: {
        Row: {
          id: number;
          label: string | null;
          source_mode: string;
          source_input: string | null;
          total_items: number;
          extracted_count: number;
          matched_count: number;
          variant_count: number;
          blocked_count: number;
          image_failed_count: number;
          applied_count: number;
          status: string;
          error_message: string | null;
          created_by: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: number;
          label?: string | null;
          source_mode: string;
          source_input?: string | null;
          total_items?: number;
          extracted_count?: number;
          matched_count?: number;
          variant_count?: number;
          blocked_count?: number;
          image_failed_count?: number;
          applied_count?: number;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: number;
          label?: string | null;
          source_mode?: string;
          source_input?: string | null;
          total_items?: number;
          extracted_count?: number;
          matched_count?: number;
          variant_count?: number;
          blocked_count?: number;
          image_failed_count?: number;
          applied_count?: number;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      snoonu_import_items: {
        Row: {
          id: number;
          batch_id: number;
          source_platform: string;
          source_url: string;
          source_product_id: string | null;
          source_image_url: string | null;
          extracted_name_en: string | null;
          extracted_name_ar: string | null;
          extracted_brand: string | null;
          extracted_category: string | null;
          extracted_subcategory: string | null;
          extracted_product_type: string | null;
          extracted_price: number | null;
          extracted_discount_price: number | null;
          extracted_currency: string | null;
          extracted_sku: string | null;
          extracted_barcode: string | null;
          extracted_description_en: string | null;
          extracted_description_ar: string | null;
          is_variant: boolean;
          variant_group_id: string | null;
          variant_type: string | null;
          variant_name: string | null;
          variant_value: string | null;
          variant_code: string | null;
          generated_sku: string | null;
          parent_sku: string | null;
          image_filename: string | null;
          image_storage_path: string | null;
          imported_image_url: string | null;
          image_status: string;
          image_quality_issues: Json | null;
          match_status: string;
          matched_product_sku: string | null;
          match_confidence: number | null;
          match_reasons: Json | null;
          review_action: string | null;
          review_notes: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          ai_enriched: boolean;
          ai_filled_fields: Json | null;
          status: string;
          error_message: string | null;
          raw_payload: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          batch_id: number;
          source_platform?: string;
          source_url: string;
          source_product_id?: string | null;
          source_image_url?: string | null;
          extracted_name_en?: string | null;
          extracted_name_ar?: string | null;
          extracted_brand?: string | null;
          extracted_category?: string | null;
          extracted_subcategory?: string | null;
          extracted_product_type?: string | null;
          extracted_price?: number | null;
          extracted_discount_price?: number | null;
          extracted_currency?: string | null;
          extracted_sku?: string | null;
          extracted_barcode?: string | null;
          extracted_description_en?: string | null;
          extracted_description_ar?: string | null;
          is_variant?: boolean;
          variant_group_id?: string | null;
          variant_type?: string | null;
          variant_name?: string | null;
          variant_value?: string | null;
          variant_code?: string | null;
          generated_sku?: string | null;
          parent_sku?: string | null;
          image_filename?: string | null;
          image_storage_path?: string | null;
          imported_image_url?: string | null;
          image_status?: string;
          image_quality_issues?: Json | null;
          match_status?: string;
          matched_product_sku?: string | null;
          match_confidence?: number | null;
          match_reasons?: Json | null;
          review_action?: string | null;
          review_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          ai_enriched?: boolean;
          ai_filled_fields?: Json | null;
          status?: string;
          error_message?: string | null;
          raw_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          batch_id?: number;
          source_platform?: string;
          source_url?: string;
          source_product_id?: string | null;
          source_image_url?: string | null;
          extracted_name_en?: string | null;
          extracted_name_ar?: string | null;
          extracted_brand?: string | null;
          extracted_category?: string | null;
          extracted_subcategory?: string | null;
          extracted_product_type?: string | null;
          extracted_price?: number | null;
          extracted_discount_price?: number | null;
          extracted_currency?: string | null;
          extracted_sku?: string | null;
          extracted_barcode?: string | null;
          extracted_description_en?: string | null;
          extracted_description_ar?: string | null;
          is_variant?: boolean;
          variant_group_id?: string | null;
          variant_type?: string | null;
          variant_name?: string | null;
          variant_value?: string | null;
          variant_code?: string | null;
          generated_sku?: string | null;
          parent_sku?: string | null;
          image_filename?: string | null;
          image_storage_path?: string | null;
          imported_image_url?: string | null;
          image_status?: string;
          image_quality_issues?: Json | null;
          match_status?: string;
          matched_product_sku?: string | null;
          match_confidence?: number | null;
          match_reasons?: Json | null;
          review_action?: string | null;
          review_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          ai_enriched?: boolean;
          ai_filled_fields?: Json | null;
          status?: string;
          error_message?: string | null;
          raw_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_variants: {
        Row: {
          id: number;
          parent_sku: string;
          variant_sku: string;
          variant_type: string;
          variant_name: string | null;
          variant_value: string;
          variant_code: string | null;
          sort_order: number;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          parent_sku: string;
          variant_sku: string;
          variant_type: string;
          variant_name?: string | null;
          variant_value: string;
          variant_code?: string | null;
          sort_order?: number;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          parent_sku?: string;
          variant_sku?: string;
          variant_type?: string;
          variant_name?: string | null;
          variant_value?: string;
          variant_code?: string | null;
          sort_order?: number;
          is_default?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      product_source_links: {
        Row: {
          id: number;
          master_sku: string;
          source_platform: string;
          source_url: string;
          source_product_id: string | null;
          import_batch_id: number | null;
          import_item_id: number | null;
          first_seen_at: string;
          last_synced_at: string;
        };
        Insert: {
          id?: number;
          master_sku: string;
          source_platform: string;
          source_url: string;
          source_product_id?: string | null;
          import_batch_id?: number | null;
          import_item_id?: number | null;
          first_seen_at?: string;
          last_synced_at?: string;
        };
        Update: {
          id?: number;
          master_sku?: string;
          source_platform?: string;
          source_url?: string;
          source_product_id?: string | null;
          import_batch_id?: number | null;
          import_item_id?: number | null;
          first_seen_at?: string;
          last_synced_at?: string;
        };
        Relationships: [];
      };
      platform_imports: {
        Row: {
          id: number;
          platform: string;
          label: string | null;
          source_mode: string;
          source_filename: string | null;
          column_mapping: Json | null;
          detected_headers: string[] | null;
          total_rows: number;
          parsed_rows: number;
          matched_rows: number;
          unmatched_rows: number;
          status: string;
          error_message: string | null;
          created_by: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: number;
          platform: string;
          label?: string | null;
          source_mode: string;
          source_filename?: string | null;
          column_mapping?: Json | null;
          detected_headers?: string[] | null;
          total_rows?: number;
          parsed_rows?: number;
          matched_rows?: number;
          unmatched_rows?: number;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: number;
          platform?: string;
          label?: string | null;
          source_mode?: string;
          source_filename?: string | null;
          column_mapping?: Json | null;
          detected_headers?: string[] | null;
          total_rows?: number;
          parsed_rows?: number;
          matched_rows?: number;
          unmatched_rows?: number;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      platform_products: {
        Row: {
          id: number;
          import_id: number;
          platform: string;
          source_row_index: number | null;
          source_product_id: string | null;
          source_url: string | null;
          source_sku: string | null;
          barcode: string | null;
          name_en: string | null;
          name_ar: string | null;
          brand: string | null;
          category: string | null;
          subcategory: string | null;
          product_type: string | null;
          price: number | null;
          discount_price: number | null;
          currency: string | null;
          stock_quantity: number | null;
          stock_status: string | null;
          platform_status: string | null;
          image_url: string | null;
          image_filename: string | null;
          variants: Json | null;
          description_en: string | null;
          description_ar: string | null;
          matched_master_sku: string | null;
          match_status: string;
          match_confidence: number | null;
          match_signals: Json | null;
          raw_payload: Json | null;
          created_at: string;
          updated_at: string;
          normalized_name: string | null;
          normalized_brand: string | null;
          name_root: string | null;
          name_token_signature: string | null;
          variant_color: string | null;
          variant_shade: string | null;
          variant_size: string | null;
          variant_volume_value: number | null;
          variant_volume_unit: string | null;
          variant_pack: number | null;
          variant_model: string | null;
          variant_type: string | null;
          image_hash: string | null;
          image_width: number | null;
          image_height: number | null;
          raw_category: string | null;
          raw_subcategory: string | null;
          category_name: string | null;
          subcategory_name: string | null;
          category_confidence: number | null;
          category_source: string | null;
          category_missing: boolean;
          snoonu_catalog: string | null;
          snoonu_category: string | null;
          snoonu_subcategory: string | null;
          snoonu_section: string | null;
          snoonu_collection: string | null;
          snoonu_menu_path: string | null;
          snoonu_catalog_source_url: string | null;
          catalog_source: string | null;
          catalog_confidence: number | null;
          catalog_checked_at: string | null;
          snoonu_branches: Json | null;
          snoonu_secondary_categories: string[] | null;
          snoonu_spi: string | null;
          snoonu_export_row: number | null;
          snoonu_export_synced_at: string | null;
          snoonu_price_ali_bin_abdullah: number | null;
          snoonu_price_al_aziziyah: number | null;
          snoonu_stock_ali_bin_abdullah: number | null;
          snoonu_stock_al_aziziyah: number | null;
          snoonu_availability_ali_bin_abdullah: boolean | null;
          snoonu_availability_al_aziziyah: boolean | null;
        };
        Insert: {
          id?: number;
          import_id: number;
          platform: string;
          source_row_index?: number | null;
          source_product_id?: string | null;
          source_url?: string | null;
          source_sku?: string | null;
          barcode?: string | null;
          name_en?: string | null;
          name_ar?: string | null;
          brand?: string | null;
          category?: string | null;
          subcategory?: string | null;
          product_type?: string | null;
          price?: number | null;
          discount_price?: number | null;
          currency?: string | null;
          stock_quantity?: number | null;
          stock_status?: string | null;
          platform_status?: string | null;
          image_url?: string | null;
          image_filename?: string | null;
          variants?: Json | null;
          description_en?: string | null;
          description_ar?: string | null;
          matched_master_sku?: string | null;
          match_status?: string;
          match_confidence?: number | null;
          match_signals?: Json | null;
          raw_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
          normalized_name?: string | null;
          normalized_brand?: string | null;
          name_root?: string | null;
          name_token_signature?: string | null;
          variant_color?: string | null;
          variant_shade?: string | null;
          variant_size?: string | null;
          variant_volume_value?: number | null;
          variant_volume_unit?: string | null;
          variant_pack?: number | null;
          variant_model?: string | null;
          variant_type?: string | null;
          image_hash?: string | null;
          image_width?: number | null;
          image_height?: number | null;
          raw_category?: string | null;
          raw_subcategory?: string | null;
          category_name?: string | null;
          subcategory_name?: string | null;
          category_confidence?: number | null;
          category_source?: string | null;
          category_missing?: boolean;
          snoonu_catalog?: string | null;
          snoonu_category?: string | null;
          snoonu_subcategory?: string | null;
          snoonu_section?: string | null;
          snoonu_collection?: string | null;
          snoonu_menu_path?: string | null;
          snoonu_catalog_source_url?: string | null;
          catalog_source?: string | null;
          catalog_confidence?: number | null;
          catalog_checked_at?: string | null;
          snoonu_branches?: Json | null;
          snoonu_secondary_categories?: string[] | null;
          snoonu_spi?: string | null;
          snoonu_export_row?: number | null;
          snoonu_export_synced_at?: string | null;
          snoonu_price_ali_bin_abdullah?: number | null;
          snoonu_price_al_aziziyah?: number | null;
          snoonu_stock_ali_bin_abdullah?: number | null;
          snoonu_stock_al_aziziyah?: number | null;
          snoonu_availability_ali_bin_abdullah?: boolean | null;
          snoonu_availability_al_aziziyah?: boolean | null;
        };
        Update: {
          id?: number;
          import_id?: number;
          platform?: string;
          source_row_index?: number | null;
          source_product_id?: string | null;
          source_url?: string | null;
          source_sku?: string | null;
          barcode?: string | null;
          name_en?: string | null;
          name_ar?: string | null;
          brand?: string | null;
          category?: string | null;
          subcategory?: string | null;
          product_type?: string | null;
          price?: number | null;
          discount_price?: number | null;
          currency?: string | null;
          stock_quantity?: number | null;
          stock_status?: string | null;
          platform_status?: string | null;
          image_url?: string | null;
          image_filename?: string | null;
          variants?: Json | null;
          description_en?: string | null;
          description_ar?: string | null;
          matched_master_sku?: string | null;
          match_status?: string;
          match_confidence?: number | null;
          match_signals?: Json | null;
          raw_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
          normalized_name?: string | null;
          normalized_brand?: string | null;
          name_root?: string | null;
          name_token_signature?: string | null;
          variant_color?: string | null;
          variant_shade?: string | null;
          variant_size?: string | null;
          variant_volume_value?: number | null;
          variant_volume_unit?: string | null;
          variant_pack?: number | null;
          variant_model?: string | null;
          variant_type?: string | null;
          image_hash?: string | null;
          image_width?: number | null;
          image_height?: number | null;
          raw_category?: string | null;
          raw_subcategory?: string | null;
          category_name?: string | null;
          subcategory_name?: string | null;
          category_confidence?: number | null;
          category_source?: string | null;
          category_missing?: boolean;
          snoonu_catalog?: string | null;
          snoonu_category?: string | null;
          snoonu_subcategory?: string | null;
          snoonu_section?: string | null;
          snoonu_collection?: string | null;
          snoonu_menu_path?: string | null;
          snoonu_catalog_source_url?: string | null;
          catalog_source?: string | null;
          catalog_confidence?: number | null;
          catalog_checked_at?: string | null;
          snoonu_branches?: Json | null;
          snoonu_secondary_categories?: string[] | null;
          snoonu_spi?: string | null;
          snoonu_export_row?: number | null;
          snoonu_export_synced_at?: string | null;
          snoonu_price_ali_bin_abdullah?: number | null;
          snoonu_price_al_aziziyah?: number | null;
          snoonu_stock_ali_bin_abdullah?: number | null;
          snoonu_stock_al_aziziyah?: number | null;
          snoonu_availability_ali_bin_abdullah?: boolean | null;
          snoonu_availability_al_aziziyah?: boolean | null;
        };
        Relationships: [];
      };
      reconciliation_runs: {
        Row: {
          id: number;
          label: string | null;
          baseline_platform: string;
          baseline_import_id: number | null;
          target_platforms: string[];
          target_import_ids: number[] | null;
          findings_total: number;
          findings_by_type: Json | null;
          status: string;
          error_message: string | null;
          created_by: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: number;
          label?: string | null;
          baseline_platform?: string;
          baseline_import_id?: number | null;
          target_platforms: string[];
          target_import_ids?: number[] | null;
          findings_total?: number;
          findings_by_type?: Json | null;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: number;
          label?: string | null;
          baseline_platform?: string;
          baseline_import_id?: number | null;
          target_platforms?: string[];
          target_import_ids?: number[] | null;
          findings_total?: number;
          findings_by_type?: Json | null;
          status?: string;
          error_message?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      reconciliation_findings: {
        Row: {
          id: number;
          run_id: number;
          master_sku: string | null;
          baseline_platform: string;
          baseline_product_id: number | null;
          target_platform: string;
          target_product_id: number | null;
          finding_type: string;
          severity: string;
          baseline_value: string | null;
          target_value: string | null;
          diff_meta: Json | null;
          suggested_action: string | null;
          resolution_status: string;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          confidence: number | null;
          candidate_pairs: Json | null;
          differing_tokens: string[] | null;
          variant_family_id: string | null;
          baseline_snapshot: Json | null;
          target_snapshot: Json | null;
          matching_reason: string | null;
        };
        Insert: {
          id?: number;
          run_id: number;
          master_sku?: string | null;
          baseline_platform?: string;
          baseline_product_id?: number | null;
          target_platform: string;
          target_product_id?: number | null;
          finding_type: string;
          severity?: string;
          baseline_value?: string | null;
          target_value?: string | null;
          diff_meta?: Json | null;
          suggested_action?: string | null;
          resolution_status?: string;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          confidence?: number | null;
          candidate_pairs?: Json | null;
          differing_tokens?: string[] | null;
          variant_family_id?: string | null;
          baseline_snapshot?: Json | null;
          target_snapshot?: Json | null;
          matching_reason?: string | null;
        };
        Update: {
          id?: number;
          run_id?: number;
          master_sku?: string | null;
          baseline_platform?: string;
          baseline_product_id?: number | null;
          target_platform?: string;
          target_product_id?: number | null;
          finding_type?: string;
          severity?: string;
          baseline_value?: string | null;
          target_value?: string | null;
          diff_meta?: Json | null;
          suggested_action?: string | null;
          resolution_status?: string;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          confidence?: number | null;
          candidate_pairs?: Json | null;
          differing_tokens?: string[] | null;
          variant_family_id?: string | null;
          baseline_snapshot?: Json | null;
          target_snapshot?: Json | null;
          matching_reason?: string | null;
        };
        Relationships: [];
      };
      platform_product_mappings: {
        Row: {
          id: number;
          baseline_platform: string;
          baseline_product_id: number | null;
          baseline_master_sku: string | null;
          baseline_source_sku: string | null;
          baseline_name_snapshot: string | null;
          target_platform: string;
          target_product_id: number | null;
          target_source_sku: string | null;
          target_source_id: string | null;
          target_name_snapshot: string | null;
          mapping_type: string;
          confidence: number | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          baseline_platform?: string;
          baseline_product_id?: number | null;
          baseline_master_sku?: string | null;
          baseline_source_sku?: string | null;
          baseline_name_snapshot?: string | null;
          target_platform: string;
          target_product_id?: number | null;
          target_source_sku?: string | null;
          target_source_id?: string | null;
          target_name_snapshot?: string | null;
          mapping_type: string;
          confidence?: number | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          baseline_platform?: string;
          baseline_product_id?: number | null;
          baseline_master_sku?: string | null;
          baseline_source_sku?: string | null;
          baseline_name_snapshot?: string | null;
          target_platform?: string;
          target_product_id?: number | null;
          target_source_sku?: string | null;
          target_source_id?: string | null;
          target_name_snapshot?: string | null;
          mapping_type?: string;
          confidence?: number | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      snoonu_catalog_sections: {
        Row: {
          id: number;
          catalog_name_en: string;
          catalog_name_ar: string | null;
          product_count: number | null;
          source_url: string | null;
          scraped_at: string;
          raw_text: string | null;
          notes: string | null;
        };
        Insert: {
          id?: number;
          catalog_name_en: string;
          catalog_name_ar?: string | null;
          product_count?: number | null;
          source_url?: string | null;
          scraped_at?: string;
          raw_text?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: number;
          catalog_name_en?: string;
          catalog_name_ar?: string | null;
          product_count?: number | null;
          source_url?: string | null;
          scraped_at?: string;
          raw_text?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      snoonu_browser_audits: {
        Row: {
          id: number;
          product_id: number;
          import_id: number | null;
          snoonu_product_url: string | null;
          snoonu_product_id: string | null;
          snoonu_product_name: string | null;
          snoonu_name_ar: string | null;
          snoonu_catalog: string | null;
          snoonu_category: string | null;
          snoonu_subcategory: string | null;
          snoonu_section: string | null;
          snoonu_menu_path: string | null;
          snoonu_price: number | null;
          snoonu_discount_price: number | null;
          snoonu_currency: string | null;
          snoonu_stock: number | null;
          snoonu_status: string | null;
          snoonu_is_visible: boolean | null;
          snoonu_image_url: string | null;
          snoonu_image_filename: string | null;
          has_options: boolean;
          option_groups: Json | null;
          variants: Json | null;
          raw_browser_snapshot: Json | null;
          audit_status: string;
          audit_confidence: number | null;
          audit_reason: string | null;
          audit_priority: number;
          audit_notes: string | null;
          audit_error_message: string | null;
          audited_at: string | null;
          audited_by: string | null;
          verified_at: string | null;
          verified_by: string | null;
          applied_at: string | null;
          applied_fields: string[] | null;
          created_at: string;
          updated_at: string;
          snoonu_branches: Json | null;
          snoonu_secondary_categories: string[] | null;
          snoonu_spi: string | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          import_id?: number | null;
          snoonu_product_url?: string | null;
          snoonu_product_id?: string | null;
          snoonu_product_name?: string | null;
          snoonu_name_ar?: string | null;
          snoonu_catalog?: string | null;
          snoonu_category?: string | null;
          snoonu_subcategory?: string | null;
          snoonu_section?: string | null;
          snoonu_menu_path?: string | null;
          snoonu_price?: number | null;
          snoonu_discount_price?: number | null;
          snoonu_currency?: string | null;
          snoonu_stock?: number | null;
          snoonu_status?: string | null;
          snoonu_is_visible?: boolean | null;
          snoonu_image_url?: string | null;
          snoonu_image_filename?: string | null;
          has_options?: boolean;
          option_groups?: Json | null;
          variants?: Json | null;
          raw_browser_snapshot?: Json | null;
          audit_status?: string;
          audit_confidence?: number | null;
          audit_reason?: string | null;
          audit_priority?: number;
          audit_notes?: string | null;
          audit_error_message?: string | null;
          audited_at?: string | null;
          audited_by?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          applied_at?: string | null;
          applied_fields?: string[] | null;
          created_at?: string;
          updated_at?: string;
          snoonu_branches?: Json | null;
          snoonu_secondary_categories?: string[] | null;
          snoonu_spi?: string | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          import_id?: number | null;
          snoonu_product_url?: string | null;
          snoonu_product_id?: string | null;
          snoonu_product_name?: string | null;
          snoonu_name_ar?: string | null;
          snoonu_catalog?: string | null;
          snoonu_category?: string | null;
          snoonu_subcategory?: string | null;
          snoonu_section?: string | null;
          snoonu_menu_path?: string | null;
          snoonu_price?: number | null;
          snoonu_discount_price?: number | null;
          snoonu_currency?: string | null;
          snoonu_stock?: number | null;
          snoonu_status?: string | null;
          snoonu_is_visible?: boolean | null;
          snoonu_image_url?: string | null;
          snoonu_image_filename?: string | null;
          has_options?: boolean;
          option_groups?: Json | null;
          variants?: Json | null;
          raw_browser_snapshot?: Json | null;
          audit_status?: string;
          audit_confidence?: number | null;
          audit_reason?: string | null;
          audit_priority?: number;
          audit_notes?: string | null;
          audit_error_message?: string | null;
          audited_at?: string | null;
          audited_by?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          applied_at?: string | null;
          applied_fields?: string[] | null;
          created_at?: string;
          updated_at?: string;
          snoonu_branches?: Json | null;
          snoonu_secondary_categories?: string[] | null;
          snoonu_spi?: string | null;
        };
        Relationships: [];
      };
      snoonu_fast_sync_runs: {
        Row: {
          id: number;
          import_id: number | null;
          source_filename: string | null;
          total_rows: number;
          inserted_rows: number;
          updated_rows: number;
          unchanged_rows: number;
          skipped_rows: number;
          missing_spi: number;
          missing_name: number;
          prices_captured: number;
          stocks_captured: number;
          availability_captured: number;
          branch_data_coverage: number | null;
          status: string;
          error_message: string | null;
          sample_changes: Json | null;
          started_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: number;
          import_id?: number | null;
          source_filename?: string | null;
          total_rows?: number;
          inserted_rows?: number;
          updated_rows?: number;
          unchanged_rows?: number;
          skipped_rows?: number;
          missing_spi?: number;
          missing_name?: number;
          prices_captured?: number;
          stocks_captured?: number;
          availability_captured?: number;
          branch_data_coverage?: number | null;
          status?: string;
          error_message?: string | null;
          sample_changes?: Json | null;
          started_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: number;
          import_id?: number | null;
          source_filename?: string | null;
          total_rows?: number;
          inserted_rows?: number;
          updated_rows?: number;
          unchanged_rows?: number;
          skipped_rows?: number;
          missing_spi?: number;
          missing_name?: number;
          prices_captured?: number;
          stocks_captured?: number;
          availability_captured?: number;
          branch_data_coverage?: number | null;
          status?: string;
          error_message?: string | null;
          sample_changes?: Json | null;
          started_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      snoonu_section_scrapes: {
        Row: {
          id: number;
          section_name: string;
          source_url: string | null;
          pages_scanned: number;
          products_found: number;
          products_matched: number;
          products_unmatched: number;
          duplicates_in_section: number;
          status: string;
          error_message: string | null;
          sample_unmatched: Json | null;
          raw_payload: Json | null;
          started_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: number;
          section_name: string;
          source_url?: string | null;
          pages_scanned?: number;
          products_found?: number;
          products_matched?: number;
          products_unmatched?: number;
          duplicates_in_section?: number;
          status?: string;
          error_message?: string | null;
          sample_unmatched?: Json | null;
          raw_payload?: Json | null;
          started_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: number;
          section_name?: string;
          source_url?: string | null;
          pages_scanned?: number;
          products_found?: number;
          products_matched?: number;
          products_unmatched?: number;
          duplicates_in_section?: number;
          status?: string;
          error_message?: string | null;
          sample_unmatched?: Json | null;
          raw_payload?: Json | null;
          started_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      snoonu_section_product_links: {
        Row: {
          id: number;
          scrape_id: number;
          section_name: string;
          product_id: number | null;
          scraped_spi: string | null;
          scraped_name: string;
          scraped_price: number | null;
          scraped_image_url: string | null;
          match_method: string;
          match_confidence: number | null;
          is_primary_section: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          scrape_id: number;
          section_name: string;
          product_id?: number | null;
          scraped_spi?: string | null;
          scraped_name: string;
          scraped_price?: number | null;
          scraped_image_url?: string | null;
          match_method: string;
          match_confidence?: number | null;
          is_primary_section?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          scrape_id?: number;
          section_name?: string;
          product_id?: number | null;
          scraped_spi?: string | null;
          scraped_name?: string;
          scraped_price?: number | null;
          scraped_image_url?: string | null;
          match_method?: string;
          match_confidence?: number | null;
          is_primary_section?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      v_snoonu_browser_audit_progress: {
        Row: {
          import_id: number | null;
          total_audited: number | null;
          pending: number | null;
          audited: number | null;
          verified: number | null;
          applied: number | null;
          skipped: number | null;
          errored: number | null;
          options_detected: number | null;
          catalog_fixed: number | null;
          price_captured: number | null;
          branches_captured: number | null;
          multi_category: number | null;
          last_audited_at: string | null;
          last_applied_at: string | null;
        };
        Relationships: [];
      };
      v_snoonu_catalog_mapping_summary: {
        Row: {
          import_id: number | null;
          platform: string | null;
          total_rows: number | null;
          mapped: number | null;
          missing: number | null;
          via_export: number | null;
          via_paste: number | null;
          via_browser: number | null;
          via_inferred: number | null;
          via_section_match: number | null;
          high_confidence: number | null;
          low_confidence: number | null;
          last_checked_at: string | null;
        };
        Relationships: [];
      };
      v_snoonu_section_coverage: {
        Row: {
          section_name: string | null;
          products_found: number | null;
          products_matched: number | null;
          products_unmatched: number | null;
          duplicates_in_section: number | null;
          last_scraped_at: string | null;
          status: string | null;
          last_scrape_id: number | null;
        };
        Relationships: [];
      };
      v_snoonu_catalog_coverage: {
        Row: {
          total_snoonu_products: number | null;
          with_category: number | null;
          missing_category: number | null;
          multi_category: number | null;
          via_section_page: number | null;
          via_browser_audit: number | null;
          via_inferred: number | null;
          high_confidence: number | null;
          low_confidence: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      recover_ai_draft: {
        Args: {
          p_draft_id: number;
          p_actor_id: string;
          p_actor_email: string;
          p_product_payload: Json;
        };
        Returns: {
          already_recovered: boolean;
          product_id: number;
          master_sku: string;
        }[];
      };
      generate_internal_barcode: {
        Args: Record<string, never>;
        Returns: string;
      };
      enqueue_snoonu_audits: {
        Args: { p_import_id: number; p_limit?: number };
        Returns: number;
      };
      search_products: {
        Args: { p_query: string; p_embedding?: string | null; p_limit?: number };
        Returns: {
          master_sku: string;
          product_name_en: string;
          product_name_ar: string;
          price: number;
          stock_quantity: number;
          image_url: string;
          score: number;
          tier: string;
        }[];
      };
      find_duplicate_candidates: {
        Args: { p_master_sku: string; p_threshold?: number };
        Returns: {
          candidate_sku: string;
          candidate_name: string;
          name_similarity: number;
          same_brand: boolean;
          same_size: boolean;
          barcode_match: boolean;
        }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
