/**
 * PRODUCTS SERVICE
 * ─────────────────────────────────────────────────────────
 * The single point of truth for product mutations.
 * All API routes, workers, and AI tools go through here.
 *
 * Responsibilities:
 *   - Create / read / update / soft-delete products
 *   - Approve / archive / block transitions
 *   - Duplicate a product safely
 *   - Bulk operations (status change, recategorize, soft-delete)
 *   - List + search with pagination/filtering
 *   - Read change history via audit log
 */

import { z } from 'zod';
import type { Database } from '@malikas/db';
import { productCreateSchema, productUpdateSchema } from '@malikas/shared';
import { BaseService, ServiceError } from './base.service';

export const listFiltersSchema = z.object({
  page: z.number().int().min(1).default(1),
  page_size: z.number().int().min(1).max(200).default(50),
  brand_id: z.number().int().optional(),
  category_id: z.number().int().optional(),
  status: z.enum(['draft', 'pending_approval', 'active', 'archived', 'blocked']).optional(),
  stock_status: z
    .enum(['in_stock', 'low_stock', 'out_of_stock', 'pre_order', 'discontinued'])
    .optional(),
  q: z.string().trim().optional(), // free-text search
  source_platform: z.string().optional(),
  include_deleted: z.boolean().default(false),
  sort: z
    .enum(['created_at_desc', 'created_at_asc', 'updated_at_desc', 'price_asc', 'price_desc'])
    .default('updated_at_desc'),
});
export type ListFilters = z.infer<typeof listFiltersSchema>;

export class ProductsService extends BaseService {
  /**
   * Create a new product. Master SKU is generated by DB trigger.
   * Editor or Owner only.
   */
  async create(input: z.infer<typeof productCreateSchema>) {
    this.requireRole(['owner', 'editor']);
    const parsed = productCreateSchema.parse(input);

    const insertPayload = {
      ...parsed,
      created_by: this.actorTag(),
      updated_by: this.actorTag(),
    };

    const { data, error } = await this.db
      .from('products')
      .insert(insertPayload)
      .select('*')
      .single();

    if (error) throw new ServiceError('CREATE_FAILED', error.message, 500, error);
    return data;
  }

  /**
   * Fetch one product with related rows.
   */
  async findBySku(master_sku: string, opts?: { include_deleted?: boolean }) {
    let query = this.db
      .from('products')
      .select(
        `
        *,
        brand:brands(id, name, name_ar, code),
        category:categories(id, name, code, priority),
        subcategory:subcategories(id, name),
        images:product_images(id, cdn_url, is_primary, width, height),
        platform_mappings(platform, platform_sku, platform_price, platform_status, last_synced_at)
      `,
      )
      .eq('master_sku', master_sku);

    if (!opts?.include_deleted) {
      query = query.is('deleted_at', null);
    }

    const { data, error } = await query.single();
    if (error || !data) throw new ServiceError('NOT_FOUND', 'Product not found', 404);
    return data;
  }

  /**
   * Paginated list with filters.
   */
  async list(filters: ListFilters) {
    const parsed = listFiltersSchema.parse(filters);
    let query = this.db
      .from('products')
      .select(
        `id, master_sku, product_name_en, product_name_ar, brand_id, category_id, price,
         discount_price, stock_quantity, stock_status, product_status, image_url, updated_at`,
        { count: 'exact' },
      );

    if (!parsed.include_deleted) {
      query = query.is('deleted_at', null);
    }
    if (parsed.brand_id) query = query.eq('brand_id', parsed.brand_id);
    if (parsed.category_id) query = query.eq('category_id', parsed.category_id);
    if (parsed.status) query = query.eq('product_status', parsed.status);
    if (parsed.stock_status) query = query.eq('stock_status', parsed.stock_status);
    if (parsed.source_platform) query = query.eq('source_platform', parsed.source_platform);
    if (parsed.q) {
      query = query.or(
        `product_name_en.ilike.%${parsed.q}%,product_name_ar.ilike.%${parsed.q}%,master_sku.ilike.%${parsed.q}%,barcode.eq.${parsed.q}`,
      );
    }

    // Sort
    const sortMap: Record<typeof parsed.sort, [string, boolean]> = {
      created_at_desc: ['created_at', false],
      created_at_asc: ['created_at', true],
      updated_at_desc: ['updated_at', false],
      price_asc: ['price', true],
      price_desc: ['price', false],
    };
    const [col, asc] = sortMap[parsed.sort];
    query = query.order(col, { ascending: asc });

    // Pagination
    const from = (parsed.page - 1) * parsed.page_size;
    const to = from + parsed.page_size - 1;
    query = query.range(from, to);

    const { data, error, count } = await query;
    if (error) throw new ServiceError('LIST_FAILED', error.message, 500);

    return {
      items: data ?? [],
      page: parsed.page,
      page_size: parsed.page_size,
      total: count ?? 0,
      has_more: (count ?? 0) > parsed.page * parsed.page_size,
    };
  }

  /**
   * Partial update. Audit log is written automatically by DB trigger.
   * Returns the updated record.
   */
  async update(master_sku: string, input: z.infer<typeof productUpdateSchema>) {
    this.requireRole(['owner', 'editor']);
    const parsed = productUpdateSchema.parse(input);

    const payload = {
      ...parsed,
      updated_by: this.actorTag(),
    };

    const { data, error } = await this.db
      .from('products')
      .update(payload)
      .eq('master_sku', master_sku)
      .is('deleted_at', null)
      .select('*')
      .single();

    if (error || !data) throw new ServiceError('UPDATE_FAILED', error?.message ?? 'No product', 404);
    return data;
  }

  /**
   * Soft-delete. Sets deleted_at + archives status.
   * Owner only.
   */
  async softDelete(master_sku: string) {
    this.requireRole(['owner']);

    const { data, error } = await this.db
      .from('products')
      .update({
        deleted_at: new Date().toISOString(),
        product_status: 'archived',
        updated_by: this.actorTag(),
      })
      .eq('master_sku', master_sku)
      .is('deleted_at', null)
      .select('master_sku')
      .single();

    if (error || !data) throw new ServiceError('DELETE_FAILED', error?.message ?? 'No product', 404);
    return { master_sku: data.master_sku, deleted: true };
  }

  /**
   * Restore a soft-deleted product.
   */
  async restore(master_sku: string) {
    this.requireRole(['owner']);

    const { data, error } = await this.db
      .from('products')
      .update({
        deleted_at: null,
        product_status: 'draft',
        updated_by: this.actorTag(),
      })
      .eq('master_sku', master_sku)
      .not('deleted_at', 'is', null)
      .select('master_sku')
      .single();

    if (error || !data) throw new ServiceError('RESTORE_FAILED', error?.message ?? 'Cannot restore', 404);
    return data;
  }

  /**
   * Duplicate a product. Creates a new master_sku, copies all fields,
   * appends "(Copy)" to the EN name. Does NOT copy platform mappings.
   */
  async duplicate(master_sku: string) {
    this.requireRole(['owner', 'editor']);

    const original = await this.findBySku(master_sku);

    const { master_sku: _, id: __, created_at, updated_at, deleted_at, embedding, ...copyable } =
      original as Database['public']['Tables']['products']['Row'];

    const payload = {
      ...copyable,
      brand_id: (original as { brand_id: number }).brand_id,
      product_name_en: `${(original as { product_name_en: string }).product_name_en} (Copy)`,
      barcode: null, // never duplicate barcode
      snoonu_sku: null,
      product_status: 'draft',
      created_by: this.actorTag(),
      updated_by: this.actorTag(),
    };
    // Remove relational expansions
    delete (payload as Record<string, unknown>).brand;
    delete (payload as Record<string, unknown>).category;
    delete (payload as Record<string, unknown>).subcategory;
    delete (payload as Record<string, unknown>).images;
    delete (payload as Record<string, unknown>).platform_mappings;

    const { data, error } = await this.db.from('products').insert(payload).select('*').single();
    if (error || !data) throw new ServiceError('DUPLICATE_FAILED', error?.message ?? '', 500);
    return data;
  }

  /**
   * Transition status: draft → pending_approval → active.
   * Enforces that critical/high validation issues block activation.
   */
  async transitionStatus(
    master_sku: string,
    next: 'pending_approval' | 'active' | 'archived' | 'blocked' | 'draft',
  ) {
    this.requireRole(['owner', 'editor']);

    // Check open critical issues before activating
    if (next === 'active') {
      const { data: criticalIssues } = await this.db
        .from('validation_issues')
        .select('id')
        .eq('master_sku', master_sku)
        .eq('status', 'open')
        .eq('severity', 'critical');
      if ((criticalIssues?.length ?? 0) > 0) {
        throw new ServiceError(
          'BLOCKED_BY_VALIDATION',
          'Cannot activate: critical validation issues open',
          409,
          { open_critical: criticalIssues!.length },
        );
      }
    }

    const { data, error } = await this.db
      .from('products')
      .update({ product_status: next, updated_by: this.actorTag() })
      .eq('master_sku', master_sku)
      .is('deleted_at', null)
      .select('master_sku, product_status')
      .single();

    if (error || !data) throw new ServiceError('TRANSITION_FAILED', error?.message ?? '', 400);
    return data;
  }

  /**
   * Approve a product: pending_approval → active.
   * Shortcut for the most common transition.
   */
  async approve(master_sku: string) {
    return this.transitionStatus(master_sku, 'active');
  }

  /**
   * Read change history (joins product_logs + price_history).
   */
  async history(master_sku: string, limit = 50) {
    const [logs, prices] = await Promise.all([
      this.db
        .from('product_logs')
        .select('field_name, old_value, new_value, actor, source, changed_at')
        .eq('master_sku', master_sku)
        .order('changed_at', { ascending: false })
        .limit(limit),
      this.db
        .from('price_history')
        .select('old_price, new_price, old_discount, new_discount, reason, actor, changed_at')
        .eq('master_sku', master_sku)
        .order('changed_at', { ascending: false })
        .limit(20),
    ]);

    return {
      audit: logs.data ?? [],
      prices: prices.data ?? [],
    };
  }

  /**
   * Bulk update — apply same change to many products.
   * Use cases: bulk recategorize, bulk activate, bulk archive.
   */
  async bulkUpdate(
    master_skus: string[],
    update: z.infer<typeof productUpdateSchema>,
  ) {
    this.requireRole(['owner', 'editor']);
    if (master_skus.length === 0) {
      throw new ServiceError('EMPTY_BULK', 'No SKUs provided', 400);
    }
    if (master_skus.length > 500) {
      throw new ServiceError('BULK_TOO_LARGE', 'Max 500 SKUs per bulk op', 400);
    }
    const parsed = productUpdateSchema.parse(update);

    const { data, error } = await this.db
      .from('products')
      .update({ ...parsed, updated_by: this.actorTag() })
      .in('master_sku', master_skus)
      .is('deleted_at', null)
      .select('master_sku');

    if (error) throw new ServiceError('BULK_FAILED', error.message, 500);
    return { updated: data?.length ?? 0, skus: (data ?? []).map((r) => r.master_sku) };
  }

  /**
   * Bulk soft-delete (Owner only).
   */
  async bulkSoftDelete(master_skus: string[]) {
    this.requireRole(['owner']);
    if (master_skus.length === 0 || master_skus.length > 500) {
      throw new ServiceError('BAD_BULK_SIZE', 'Provide 1..500 SKUs', 400);
    }

    const { data, error } = await this.db
      .from('products')
      .update({
        deleted_at: new Date().toISOString(),
        product_status: 'archived',
        updated_by: this.actorTag(),
      })
      .in('master_sku', master_skus)
      .is('deleted_at', null)
      .select('master_sku');

    if (error) throw new ServiceError('BULK_DELETE_FAILED', error.message, 500);
    return { deleted: data?.length ?? 0 };
  }
}
