/**
 * POST /api/import/[batchId]/commit
 *
 * Body: { row_ids?: number[], skip_ids?: number[] }
 *
 * Commits approved staged rows into the products + platform_mappings
 * + product_images tables. Sets batch status to 'completed'.
 * Marks each insert with source = `import_batch:${batchId}` so rollback works.
 */
import { z } from 'zod';
import { NextRequest } from 'next/server';
import type { Database } from '@malikas/db';
import { ok, err, withErrorHandling } from '@/lib/api-response';
import { createAdminSupabaseClient } from '@/lib/supabase/server';

const Body = z.object({
  row_ids: z.array(z.number()).optional(),
  skip_ids: z.array(z.number()).optional(),
});

export const POST = withErrorHandling(
  async (req: NextRequest, ctx: { params: { batchId: string } }) => {
    const batchId = parseInt(ctx.params.batchId, 10);
    if (!Number.isFinite(batchId)) return err('BAD_ID', 'Invalid batch id', 400);

    const json = await req.json();
    const body = Body.parse(json);

    const admin = createAdminSupabaseClient();

    const { data: rows, error: rowsErr } = await admin
      .from('import_errors')
      .select('*')
      .eq('batch_id', batchId);

    if (rowsErr || !rows) return err('DB_ERROR', rowsErr?.message ?? 'No rows', 500);

    const skip = new Set(body.skip_ids ?? []);
    const onlyIncluded = body.row_ids ? new Set(body.row_ids) : null;

    const toCommit = rows.filter(
      (r) =>
        !skip.has(r.id) &&
        (!onlyIncluded || onlyIncluded.has(r.id)) &&
        (r.error_type === 'auto_import' || r.error_type === 'review_required'),
    );

    if (toCommit.length === 0) {
      return err('NOTHING_TO_COMMIT', 'No rows selected for commit', 400);
    }

    const inserted: Array<{ master_sku: string; raw_index: number }> = [];
    const failed: Array<{ raw_index: number; reason: string }> = [];

    for (const row of toCommit) {
      const staged = row.raw_data as Record<string, unknown>;
      const cleaned = (staged.cleaned ?? {}) as Record<string, unknown>;
      const category = (staged.category ?? {}) as Record<string, unknown>;

      // master_sku is auto-generated by the DB trigger
      const insertPayload = {
        product_name_en: cleaned.product_name_en,
        product_name_ar: cleaned.product_name_ar,
        brand_id: staged.brand_id ?? null,
        category_id: category.category_id,
        subcategory_id: category.subcategory_id ?? null,
        product_type: category.product_type ?? null,
        snoonu_sku: cleaned.snoonu_sku ?? null,
        barcode: cleaned.barcode ?? null,
        size: cleaned.size ?? null,
        variant: cleaned.variant ?? null,
        color: cleaned.color ?? null,
        price: cleaned.price ?? 0,
        discount_price: cleaned.discount_price ?? null,
        cost: cleaned.cost ?? null,
        stock_quantity: cleaned.stock_quantity ?? 0,
        description_en: cleaned.description_en ?? null,
        description_ar: cleaned.description_ar ?? null,
        image_url: cleaned.image_url ?? null,
        source_platform: cleaned.source_platform ?? 'import',
        product_status: (staged.validation as Record<string, unknown>)?.status ?? 'draft',
        created_by: `import_batch:${batchId}`,
        updated_by: `import_batch:${batchId}`,
      };

      const { data, error: insertErr } = await admin
        .from('products')
        .insert(insertPayload as Database['public']['Tables']['products']['Insert'])
        .select('master_sku')
        .single();

      if (insertErr || !data) {
        failed.push({ raw_index: row.row_number ?? 0, reason: insertErr?.message ?? 'unknown' });
        continue;
      }

      inserted.push({ master_sku: data.master_sku, raw_index: row.row_number ?? 0 });
    }

    // Update batch summary
    await admin
      .from('import_batches')
      .update({
        status: failed.length === 0 ? 'completed' : 'completed',
        success_rows: inserted.length,
        error_rows: failed.length,
        completed_at: new Date().toISOString(),
        error_summary: failed.length > 0 ? failed : null,
      })
      .eq('id', batchId);

    return ok({
      batch_id: batchId,
      inserted: inserted.length,
      failed: failed.length,
      details: { inserted, failed },
    });
  },
);
