-- ============================================================================
-- PHASE 6.5 — Bilingual AI fields + brand additions
-- ============================================================================
-- Adds:
--   1. products.usage_en  (TEXT, nullable)
--   2. products.usage_ar  (TEXT, nullable)
--   3. Brands: Dr.Pen, Rhode (with K-beauty / premium tier mapping)
--
-- Idempotent. Safe to re-run.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Add usage columns (no breaking change — nullable, default NULL)
-- ----------------------------------------------------------------------------

ALTER TABLE products ADD COLUMN IF NOT EXISTS usage_en TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS usage_ar TEXT;

COMMENT ON COLUMN products.usage_en IS 'Step-by-step product usage instructions in English. Generated by AI Autofill, editable by admin.';
COMMENT ON COLUMN products.usage_ar IS 'Same usage instructions in Gulf-natural Arabic. Generated by AI Autofill.';

-- ----------------------------------------------------------------------------
-- 2. Extend the product_logs trigger to track these new fields
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION log_product_changes()
RETURNS TRIGGER AS $$
DECLARE
    tracked_fields TEXT[] := ARRAY[
        'product_name_en','product_name_ar','brand_id','category_id','subcategory_id',
        'product_type','variant','color','size','price','discount_price','cost',
        'stock_quantity','stock_status','product_status','image_url',
        'description_en','description_ar','keywords_en','keywords_ar',
        'usage_en','usage_ar'
    ];
    f TEXT;
    old_val JSONB;
    new_val JSONB;
BEGIN
    FOREACH f IN ARRAY tracked_fields LOOP
        old_val := to_jsonb(OLD) -> f;
        new_val := to_jsonb(NEW) -> f;
        IF old_val IS DISTINCT FROM new_val THEN
            INSERT INTO product_logs(master_sku, field_name, old_value, new_value, actor, source)
            VALUES (NEW.master_sku, f, old_val, new_val,
                    COALESCE(NEW.updated_by, 'system'), 'trigger');
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 3. Add brands referenced in updated AI prompt
-- ----------------------------------------------------------------------------

INSERT INTO brands (name, name_ar, code, country_origin) VALUES
    ('Dr.Pen',  'دكتور بن',  'DRP', 'South Korea'),
    ('Rhode',   'رود',       'RHD', 'USA')
ON CONFLICT (name) DO NOTHING;

-- Dr.Pen → Beauty Tools (microneedling devices)
INSERT INTO category_rules (brand_id, category_id, confidence)
SELECT b.id, 7, 1.00 FROM brands b WHERE b.name = 'Dr.Pen'
ON CONFLICT (brand_id) DO NOTHING;

-- Rhode → Korean Skincare-style premium skincare (Hailey Bieber brand). Many
-- of their lip+skin products are in the moisturizer/lip-care space — keep as
-- Korean Skincare bucket for now since we don't have a "Western Skincare" cat.
INSERT INTO category_rules (brand_id, category_id, confidence)
SELECT b.id, 1, 0.85 FROM brands b WHERE b.name = 'Rhode'
ON CONFLICT (brand_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 4. Verify
-- ----------------------------------------------------------------------------
--   SELECT column_name FROM information_schema.columns
--    WHERE table_name = 'products' AND column_name IN ('usage_en','usage_ar');
--   SELECT name FROM brands WHERE name IN ('Dr.Pen','Rhode');
